##
## Makefile for  in /home/fortevg/rendu/CPE/CPE_2015_corewar
## 
## Made by Forteville Gabriel
## Login   <fortevg@epitech.net>
## 
## Started on  Thu Mar 17 13:51:19 2016 Forteville Gabriel
## Last update Sun Mar 27 15:27:35 2016 Hugo Willaume
##

all:
	make -C ./asm/
	make -C ./VM/

clean:
	make -C ./asm/ clean
	make -C ./VM/ clean
fclean:
	make -C ./asm/ fclean
	make -C ./VM/ fclean
re:
	make -C ./asm/ re
	make -C ./VM/ re
